FROM python:3.9-slim

WORKDIR /app

COPY . .

RUN pip3 install -r 03_Notebooks/03_Sistema/app_credit_risk/requirements.txt
RUN pip3 install protobuf==3.20.0 altair==4.1.0 click==8.0.3

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["streamlit", "run", "03_Notebooks/03_Sistema/app_credit_risk/app_credit_risk.py", "--server.port=8501", "--server.address=0.0.0.0"]

